name: Deploy Apps
on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: "17"
    
jobs:
  code-scan:
    name: sast-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: checkout code

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: scan code with codeql
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload file SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif