name: Deploy Apps
on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: "17"
  TAGS: "v1.1.0"
  CONTAINER_REGISTRY: "smodou"
  REPOSITORY_NAME: "gowebapp"
    
jobs:
  code-analysis:
    name: sast-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build Java Project
        run: mvn clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: false # Stop workflow if CodeQl analysis is false
        with:
          upload: false # Disable auto upload result, set true when SARIF is enabled
          
      #- name: Upload file SARIF
      #  uses: github/codeql-action/upload-sarif@v3 
      #  with:
      #    sarif_file: results.sarif # CodeQL analyses from advanced configurations cannot Upload file when the default setup is enabled

  contenerized:
    runs-on: ubuntu-latest
    needs: code-analysis # This ensures this job runs only if code-analysis is successful
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --build-arg DOCKER_CONTENT_TRUST=1 . -t ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ env.TAGS }}

      - name: Scan docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ env.TAGS }}'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'