name: Deploy Apps
on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: "17"
    
jobs:
  code-scan:
    name: sast-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'kotlin' ]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          architecture: x64

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build Java Project
        run: mvn clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
          
      - name: Upload file SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif